In [ ]:
import numpy as np

scores = np.random.randint(50, 101,size=(50, 5))
scores

In [3]:
import pandas as pd

df = pd.DataFrame(scores,
            index = [f"學生{i+1}" for i in range(50)],
            columns = ["國文","英文","數學","地理","歷史"]
)
df

       國文   英文   數學   地理   歷史
學生1    75   76   74   82   73
學生2    78   84   90   98   52
學生3    69   81   84  100   87
學生4    74   78   66   78   58
學生5    70   83   73   77   86
學生6    98   68   86   59   69
學生7    93   76   64   51   52
學生8    62   93   98   62   75
學生9    85   74   77   79   64
學生10   58   60   79   74   70
學生11   62   50   62   94   79
學生12   65   92   74   59   61
學生13   51   53   60   74   93
學生14   73  100   54   98   54
學生15   95   58   85   99   58
學生16   94   76   88   70   58
學生17   59   94   53   54   86
學生18   81   80   77   52   68
學生19   61   65   51   80   70
學生20   57   58   50   67   82
學生21  100   57   70   61   97
學生22   73   50   53   66   98
學生23   92   74   76   64   99
學生24   68   83  100   59   54
學生25   56   76   84   87   61
學生26   76   63   86   55   94
學生27   77  100   89   67   86
學生28   94   88   80   77   83
學生29   64   80   99   85   88
學生30   76   52   92   71   71
學生31   53   92   58   55   60
學生32   97   63   97   82   74
學生33   70   87   76   72  100
學生34   83   84   91   59   50
學生35   93   88  100   53   52
學生36   77   84   64   55   87
學生37   55   90   82   75  100
學生38   75   85   59   92   73
學生39   96   79   57   82   54
學生40   72   96   51   62   92
學生41   57   80   73   54   76
學生42   73   65   91   55   81
學生43   73   84   72   81   73
學生44   58   93   65   52   94
學生45   74   59   84   70   88
學生46   74   60   92   77   94
學生47   50   61   83   72   91
學生48   58   90  100   54   95
學生49   80   63   79   68   65
學生50   77   99   79   70   84