In [1]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位: ['國文', '英文', '數學', '自然', '社會','總分','平均','排名']
#索引: ['學生' + str(i) for i in range(1, 51)]
#建立DataFrame
import numpy as np
import pandas as pd 

def build_scores_dataframe(scores):
    df = pd.DataFrame(scores,
                      columns=['國文', '英文', '數學', '自然', '社會'],
                      index=['學生' + str(i) for i in range(1, 51)])
    df.index.name = '學生'
    df.columns.name = '科目'
    sum_values = df.sum(axis=1)
    mean_values = df.mean(axis=1)
    df['總分'] = sum_values
    df['平均'] = mean_values
    rank_values = sum_values.rank(method='min', ascending=False)
    df['排名'] = rank_values
    return df

scores = np.random.randint(50,101,size=(50, 5))
df = build_scores_dataframe(scores)
df

科目    國文   英文  數學   自然   社會   總分    平均    排名
學生
學生1   61   93  51   86   89  380  76.0  26.0
學生2   82   98  76   80   82  418  83.6   6.0
學生3   51   67  69   97  100  384  76.8  23.0
學生4   86   63  60   67   74  350  70.0  38.0
學生5   75   72  66   64   57  334  66.8  44.0
學生6   90   94  54   69   51  358  71.6  35.0
學生7   55   82  68   53   69  327  65.4  47.0
學生8   60   84  53   87   67  351  70.2  37.0
學生9   65   59  82   74   70  350  70.0  38.0
學生10  64   52  71   92   54  333  66.6  45.0
學生11  95   53  67   56   58  329  65.8  46.0
學生12  60   63  82   92   86  383  76.6  24.0
學生13  81   56  94   69   95  395  79.0  17.0
學生14  67   51  84   56   79  337  67.4  43.0
學生15  67   86  67   91   59  370  74.0  29.0
學生16  61   73  76   60   87  357  71.4  36.0
學生17  88   89  96  100   80  453  90.6   1.0
學生18  89   78  67   53   57  344  68.8  40.0
學生19  89   74  66   52   60  341  68.2  42.0
學生20  51   75  87   91   59  363  72.6  32.0
學生21  58   89  91   77   77  392  78.4  19.0
學生22  99   99  70   66   98  432  86.4   4.0
學生23  87   55  90   71   74  377  75.4  27.0
學生24  88   99  97   74   77  435  87.0   3.0
學生25  63   79  98   70   89  399  79.8  15.0
學生26  97   90  91   50   65  393  78.6  18.0
學生27  74   91  87   50   99  401  80.2  13.0
學生28  97   97  72   78   67  411  82.2   9.0
學生29  79   64  58   89   79  369  73.8  30.0
學生30  62   92  93   66   76  389  77.8  20.0
學生31  94   67  57   78   87  383  76.6  24.0
學生32  65   59  62   65   56  307  61.4  49.0
學生33  84   55  68   59   59  325  65.0  48.0
學生34  80   97  96   84   51  408  81.6  10.0
學生35  57   71  86   51   78  343  68.6  41.0
學生36  94   83  83   63   91  414  82.8   8.0
學生37  75   78  73   95   97  418  83.6   6.0
學生38  58   59  72   87   91  367  73.4  31.0
學生39  58  100  83   69   86  396  79.2  16.0
學生40  89   66  96   70   66  387  77.4  21.0
學生41  98   74  92   89   97  450  90.0   2.0
學生42  89   73  55   64   79  360  72.0  33.0
學生43  93  100  53   78   83  407  81.4  12.0
學生44  87   88  85   88   53  401  80.2  13.0
學生45  53   81  52   98   75  359  71.8  34.0
學生46  67   56  62   60   61  306  61.2  50.0
學生47  54   63  96   89   83  385  77.0  22.0
學生48  95   65  62   87   99  408  81.6  10.0
學生49  89   71  93   85   91  429  85.8   5.0
學生50  67   95  50   85   74  371  74.2  28.0

In [16]:
#選擇欄位
df1 = df[['國文', '英文', '數學', '自然', '社會']]
df1

科目    國文   英文  數學   自然   社會
學生
學生1   61   93  51   86   89
學生2   82   98  76   80   82
學生3   51   67  69   97  100
學生4   86   63  60   67   74
學生5   75   72  66   64   57
學生6   90   94  54   69   51
學生7   55   82  68   53   69
學生8   60   84  53   87   67
學生9   65   59  82   74   70
學生10  64   52  71   92   54
學生11  95   53  67   56   58
學生12  60   63  82   92   86
學生13  81   56  94   69   95
學生14  67   51  84   56   79
學生15  67   86  67   91   59
學生16  61   73  76   60   87
學生17  88   89  96  100   80
學生18  89   78  67   53   57
學生19  89   74  66   52   60
學生20  51   75  87   91   59
學生21  58   89  91   77   77
學生22  99   99  70   66   98
學生23  87   55  90   71   74
學生24  88   99  97   74   77
學生25  63   79  98   70   89
學生26  97   90  91   50   65
學生27  74   91  87   50   99
學生28  97   97  72   78   67
學生29  79   64  58   89   79
學生30  62   92  93   66   76
學生31  94   67  57   78   87
學生32  65   59  62   65   56
學生33  84   55  68   59   59
學生34  80   97  96   84   51
學生35  57   71  86   51   78
學生36  94   83  83   63   91
學生37  75   78  73   95   97
學生38  58   59  72   87   91
學生39  58  100  83   69   86
學生40  89   66  96   70   66
學生41  98   74  92   89   97
學生42  89   73  55   64   79
學生43  93  100  53   78   83
學生44  87   88  85   88   53
學生45  53   81  52   98   75
學生46  67   56  62   60   61
學生47  54   63  96   89   83
學生48  95   65  62   87   99
學生49  89   71  93   85   91
學生50  67   95  50   85   74

In [ ]:
s = df1.loc['學生1']
less_than_60_series = s[s<60]
#取出不及格的科目
failing_subjects = less_than_60_series.index.tolist()
failing_subjects
#取出不及格科目的分數
failing_scores = less_than_60_series.tolist()
failing_scores
#建立一個Series,值要轉換為字串,如果有多個值則用逗號分隔
failing_scores_str = ','.join(map(str, failing_scores))
failing_subjects_str = ','.join(failing_subjects)
pd.Series([failing_scores_str, failing_subjects_str], index=['分數', '不及格科目'])

分數       51
不及格科目    國文
dtype: object

In [ ]:
def apply_statistics(s):
    less_than_60_series = s[s<60]
    #不及格科目數量
    failing_subjects_count = less_than_60_series.count()
    #取出不及格的科目
    failing_subjects = less_than_60_series.index.tolist()
    
    #取出不及格科目的分數
    failing_scores = less_than_60_series.tolist()
    
    #建立一個Series,值要轉換為字串,如果有多個值則用逗號分隔
    failing_scores_str = ','.join(map(str, failing_scores))
    failing_subjects_str = ','.join(failing_subjects)
    return pd.Series([failing_subjects_count,failing_subjects_str,failing_scores_str], index=['不及格科目數量', '不及格科目', '分數'])


df2 = df1.apply(apply_statistics, axis=1)
df2

In [ ]:
#df要和df2合併
df_merged = pd.concat([df, df2], axis=1)
df_merged

In [24]:
#df_merged請儲存為excel檔
df_merged.to_excel('df_merged.xlsx')