In [10]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位: ['國文', '英文', '數學', '自然', '社會','總分','平均','排名']
#索引: ['學生' + str(i) for i in range(1, 51)]
#建立DataFrame
import numpy as np
import pandas as pd 

def build_scores_dataframe(scores):
    df = pd.DataFrame(scores,
                      columns=['國文', '英文', '數學', '自然', '社會'],
                      index=['學生' + str(i) for i in range(1, 51)])
    df.index.name = '學生'
    df.columns.name = '科目'
    sum_values = df.sum(axis=1)
    mean_values = df.mean(axis=1)
    df['總分'] = sum_values
    df['平均'] = mean_values
    rank_values = sum_values.rank(method='min', ascending=False)
    df['排名'] = rank_values
    return df

In [14]:
scores = np.random.randint(50,101,size=(50, 5))
df = build_scores_dataframe(scores)
df
#AI建立一個function
#依據df
#建立1個統計的DataFrame
#欄位: ['國文', '英文', '數學', '自然', '社會']
#欄位: ['平均', '最高', '最低', '中間值']


df

科目    國文   英文   數學   自然  社會   總分    平均    排名
學生
學生1   61   89   78   75  78  381  76.2  25.0
學生2   98   59   72   79  89  397  79.4  18.0
學生3   68   73   87   86  54  368  73.6  30.0
學生4   52   85   65   72  78  352  70.4  38.0
學生5   87   87   97   93  94  458  91.6   3.0
學生6   65   74   53   73  72  337  67.4  44.0
學生7   86   75   88   63  98  410  82.0  11.0
學生8   88   59   54   70  83  354  70.8  36.0
學生9   89   54   55   74  67  339  67.8  43.0
學生10  69   61   88  100  65  383  76.6  23.0
學生11  85   60   99   72  87  403  80.6  13.0
學生12  69   65   53   62  55  304  60.8  50.0
學生13  87   50   55   97  75  364  72.8  32.0
學生14  93   65   61   51  88  358  71.6  34.0
學生15  78   93   87   58  51  367  73.4  31.0
學生16  76   73   80   92  92  413  82.6   8.0
學生17  75   50   54   77  64  320  64.0  48.0
學生18  79   71   54   60  94  358  71.6  34.0
學生19  75   57   75   70  67  344  68.8  40.0
學生20  93   56   75   90  82  396  79.2  20.0
學生21  54   86   74   69  64  347  69.4  39.0
學生22  74  100   93   93  77  437  87.4   6.0
學生23  58   64   90   98  90  400  80.0  15.0
學生24  63   63   73   58  96  353  70.6  37.0
學生25  99   67   84   98  94  442  88.4   5.0
學生26  54   67   71   79  51  322  64.4  47.0
學生27  76   87   50   57  50  320  64.0  48.0
學生28  84   92   96   58  73  403  80.6  13.0
學生29  78   82   97   92  68  417  83.4   7.0
學生30  63   68   65   52  95  343  68.6  41.0
學生31  77   67   68   95  92  399  79.8  16.0
學生32  82   99   80   93  91  445  89.0   4.0
學生33  84   97  100   87  92  460  92.0   2.0
學生34  73   77   73   64  56  343  68.6  41.0
學生35  64   99   51   93  91  398  79.6  17.0
學生36  89   76   95   50  73  383  76.6  23.0
學生37  61   90   69   98  72  390  78.0  21.0
學生38  96   79   60   80  74  389  77.8  22.0
學生39  74   54   92   50  67  337  67.4  44.0
學生40  80   78   54   50  63  325  65.0  46.0
學生41  68   52   85   88  67  360  72.0  33.0
學生42  73   87   83   80  90  413  82.6   8.0
學生43  78   86   57   59  90  370  74.0  27.0
學生44  81   98   56   97  73  405  81.0  12.0
學生45  50   74   58   99  91  372  74.4  26.0
學生46  97   58  100   74  68  397  79.4  18.0
學生47  96  100   87   89  91  463  92.6   1.0
學生48  79   98   74   71  91  413  82.6   8.0
學生49  64   91   98   53  63  369  73.8  29.0
學生50  80   86   59   65  80  370  74.0  27.0

In [ ]:
#建立1個統計的DataFrame
def create_statistics_dataframe(df):
    cols = ['國文', '英文', '數學', '自然', '社會']
    stats = df[cols].agg(['mean', 'max', 'min', 'median'])
    stats.index = ['平均', '最高', '最低', '中間值']
    return stats
create_statistics_dataframe(df)

科目      國文      英文     數學      自然      社會
平均   71.46   71.92  71.84   74.92   70.58
最高   99.00  100.00  99.00  100.00  100.00
最低   50.00   50.00  50.00   50.00   50.00
中間值  71.50   69.50  66.50   74.50   68.50